CHANGELOG.md, docs/05-dataclasses.md, src/validataclass/helpers/__init__.py, src/validataclass/helpers/unset_value.py, tests/helpers/dataclasses_test.py, tests/validators/dataclass_validator_test.py
This PR adds two type aliases related to `UnsetValueType` for convenience:
- `OptionalUnset[T]` == `Union[T, UnsetValueType]` \
(used for fields with `DefaultUnset`)
- `OptionalUnsetNone[T]` == `OptionalUnset[Optional[T]]` == `Union[T, NoneType, UnsetValueType]` \
(used for fields that can be both None and UnsetValue, e.g. a `Noneable` field with `DefaultUnset`)
=> Add type aliases OptionalUnset[T] and OptionalUnsetNone[T]

CHANGELOG.md, src/validataclass/helpers/dataclasses.py, tests/helpers/dataclasses_test.py, tests/validators/dict_validator_test.py
Solves #26.
- `@validataclass` decorator detects fields with validator but without type annotations and will raise errors about that now.
- `@validataclass` allows empty dataclasses now (raised an AttributeError before).
=> Allow empty dataclasses and detect missing annotations

src/validataclass/helpers/__init__.py, src/validataclass/helpers/dataclass_mixins.py, tests/helpers/dataclass_mixins_test.py
The `to_dict()` method from `ValidataclassMixin` now removes all fields with `UnsetValue` from the dictionary, unless the optional parameter `keep_unset_values` is True.
=> ValidataclassMixin: Remove UnsetValues in to_dict()

.github/workflows/tests.yml, CHANGELOG.md, Makefile, setup.cfg, src/validataclass/exceptions/common_exceptions.py, src/validataclass/helpers/dataclasses.py, src/validataclass/validators/__init__.py, tests/helpers/dataclass_mixins_test.py, tox.ini
This PR adds "official support" for Python 3.10, i.e. it adds a test environment for Python 3.10 and fixes a small issue in the unit tests.
(Also smuggled in some unrelated minor fixes.)
=> Official support for Python 3.10

CHANGELOG.md, docs/03-basic-validators.md, src/validataclass/exceptions/__init__.py, src/validataclass/exceptions/number_exceptions.py, src/validataclass/validators/integer_validator.py, tests/validators/integer_validator_test.py
This PR adds a new optional parameter `allow_strings` to the IntegerValidator to accept integers as strings (e.g. `"123"` -> `123`).
Closes #17.
=> IntegerValidator: Implement allow_strings parameter

CHANGELOG.md, docs/03-basic-validators.md, src/validataclass/validators/__init__.py, src/validataclass/validators/float_to_decimal_validator.py, src/validataclass/validators/numeric_validator.py, tests/validators/decimal_validator_test.py, tests/validators/float_to_decimal_validator_test.py, tests/validators/numeric_validator_test.py
This PR reimplements the `FloatToDecimalValidator` based on the `DecimalValidator` instead of the `FloatValidator`, which simplifies the code a bit and makes `NumberRangeError` exceptions more consistent ("min_value" and "max_value" in the exceptions are now always decimal strings instead of floats or decimals depending on the type of input value).
It also adds the `NumericValidator` as a shortcut for `FloatToDecimalValidator(allow_integers=True, allow_strings=True)`, so it parses floats, integers and decimal strings and always returns Decimals.
=> Reimplement FloatToDecimalValidator and add NumericValidator

.github/workflows/test-reports.yml, .github/workflows/tests.yml
This PR should (hopefully) allow the GitHub actions workflow to publish test reports from formed repositories.
=> Split up GitHub workflow to allow test reports from forked repositories

src/validataclass/validators/url_validator.py, tests/validators/url_validator_test.py
=> UrlValidator: Add `allow_empty` and `max_length` parameter

docs/03-basic-validators.md, src/validataclass/validators/__init__.py, src/validataclass/validators/big_integer_validator.py, src/validataclass/validators/integer_validator.py, tests/test_utils.py, tests/validators/big_integer_validator_test.py, tests/validators/integer_validator_test.py
This PR sets defaults for `min_value` and `max_value` of the `IntegerValidator` to limit input by default to 32-bit integers, according to #42.
_Technically_ this is a breaking change, but it's unlikely that it causes problems (also, we are still at version 0.x anyway).
=> IntegerValidator: Default min/max values for 32 bit integers (#42)

src/validataclass/validators/noneable.py, tests/validators/noneable_test.py
This PR implements a type check on construction for the `Noneable` meta validator.
Resolves #38.
=> Noneable: Raise exception if wrapped validator has invalid type (#38)

docs/03-basic-validators.md, src/validataclass/validators/decimal_validator.py, tests/validators/decimal_validator_test.py
This PR for the `DecimalValidator` allows the `min_value` and `max_value` parameters to be specified as integers.
It's still not allowed to specify them as floats, though, because floats are inprecise in their nature (though specifying floats probably would work, your type checker would just complain about it).
=> DecimalValidator: Allow min_value/max_value as integers

docs/03-basic-validators.md, src/validataclass/validators/regex_validator.py, tests/validators/regex_validator_test.py
This PR adds a parameter to specify a custom exception class in the `RegexValidator`, see #44.
I decided against renaming the existing `custom_error_code` parameter and simply named the new parameter `custom_error_class` as well, to avoid an unnecessary breaking change.
=> RegexValidator: Add support for custom exception classes (#44)

docs/03-basic-validators.md, docs/04-lists-and-dicts.md, docs/05-dataclasses.md, src/validataclass/exceptions/__init__.py, src/validataclass/exceptions/common_exceptions.py, src/validataclass/validators/__init__.py, src/validataclass/validators/noneable.py, src/validataclass/validators/reject_validator.py, tests/validators/noneable_test.py, tests/validators/reject_validator_test.py
This PR implements the special `RejectValidator` that rejects any input (see #20).
I also decided to drop the term "meta validators" and just call them special validators (or in wrapper validator in case of `Noneable`), since the word "meta" doesn't really fit here.
=> New validator: RejectValidator

docs/03-basic-validators.md, src/validataclass/helpers/unset_value.py, src/validataclass/validators/__init__.py, src/validataclass/validators/none_to_unset_value.py, src/validataclass/validators/noneable.py, tests/helpers/dataclass_mixins_test.py, tests/helpers/unset_value_test.py, tests/validators/none_to_unset_value_test.py, tests/validators/noneable_test.py, tests/validators/regex_validator_test.py
This PR adds a new special validator `NoneToUnsetValue`, which is just a shortcut for `Noneable(validator, default=UnsetValue)`.
There also is a minor addition in the `UnsetValue` object (it explicitly implements `__eq__` now and has unit tests for that).
=> New validator: NoneToUnsetValue

src/validataclass/exceptions/__init__.py, src/validataclass/exceptions/common_exceptions.py, src/validataclass/validators/dataclass_validator.py, tests/exceptions/common_exceptions_test.py, tests/validators/dataclass_validator_test.py
This PR changes the DataclassValidator to catch ONLY `ValidationError` exceptions. Other exceptions are ignored, so they bubble up to the application. See #58.
This PR also **removes** the `InternalValidationError` exception class, since now it is not needed anymore.
These technically are breaking changes, but I doubt that any code depended on either the handling of non-ValidationError exceptions in the DataclassValidator, nor used the InternalValidationError anywhere.
=> DataclassValidator: Don't catch non-ValidationError exceptions

src/validataclass/dataclasses/defaults.py, src/validataclass/dataclasses/validataclass_field.py, src/validataclass/validators/dict_validator.py, tests/dataclasses/_helpers.py, tests/dataclasses/defaults_test.py, tests/dataclasses/validataclass_field_test.py, tests/dataclasses/validataclass_test.py, tests/validators/dataclass_validator_test.py
This PR fixes a bug where `Default` objects with mutable values, for example lists (`Default([])`), would cause errors when defining validataclasses.
This bug was introduced in the latest release (0.6.0) due to the reimplementation of Defaults.
The PR changes how `default` and `default_factory` are set in validataclass fields. The `Default` class and subclasses have also been a bit extended and now feature a `needs_factory()` method (which should return True if the Default represents any value that changes whenever the default value is retrieved, e.g. a list would always be deepcopied). Also, `Default` implements `__eq__` now.
I also added a few tests that would have detected this bug before the release.
=> Fix Default objects with mutable values (e.g. lists)

docs/05-dataclasses.md, src/validataclass/dataclasses/validataclass.py, tests/dataclasses/validataclass_test.py
This PR fixes a bug in the validataclass decorator related to multiple inheritance.
The following code was not working:
```
@validataclass
class BaseA:
field_a: int = IntegerValidator()
@validataclass
class BaseB:
field_b: int = IntegerValidator()
@validataclass
class SubClass(BaseB, BaseA):
field_a: int = Default(42)  # raises: Dataclass field "field_a" must specify a Validator.
field_b: int = Default(42)  # this works fine
```
So, when overriding a field from a base class, the existing properties are only recognized if the base class has the highest MRO (in this case: only fields from BaseB can be overridden correctly).
With this bugfix, existing fields from *all* base classes will be considered when constructing the dataclass fields.
=> Fix overriding of existing field properties in validataclasses with multiple inheritance

src/validataclass/helpers/__init__.py, src/validataclass/helpers/unset_value.py, tests/helpers/unset_value_test.py
This PR adds a small helper function `unset_to_none()` (from `validataclass.helpers`).
The function takes any value as input and returns `None` if the input is `UnsetValue`, or the unmodified value in any other case.
=> Add helper function unset_to_none()

requirements.txt, setup.cfg, src/validataclass/dataclasses/validataclass.py
This PR applies the new `@dataclass_transform` decorator (PEP 681) on the `@validataclass` decorator.
Since this decorator was only introduced in Python 3.11, we're using the typing-extensions library here which backports some newer typing features.
Solves #75.
=> Use @dataclass_transform decorator on @validataclass decorator via typing-extensions (#75)

docs/03-basic-validators.md, src/validataclass/validators/datetime_validator.py, tests/validators/datetime_validator_test.py
This PR adds a new boolean parameter `discard_milliseconds` to `DateTimeValidator`. (See #74.)
If set, milli- and microseconds will be set to 0 in the output datetime.
=> DateTimeValidator: Add discard_milliseconds parameter (#74)

docs/03-basic-validators.md, src/validataclass/validators/__init__.py, src/validataclass/validators/any_of_validator.py, src/validataclass/validators/dataclass_validator.py, src/validataclass/validators/enum_validator.py, src/validataclass/validators/list_validator.py, tests/validators/any_of_validator_test.py, tests/validators/enum_validator_test.py
This PR contains some smaller improvements:
- `ListValidator` is now a generic class (e.g. `ListValidator[int]`)
- `EnumValidator` is now a generic class (e.g. `EnumValidator[ExampleEnum]`) (#73)
- `AnyOfValidator` and `EnumValidator` now accept the `allowed_values` and `allowed_types` parameters as any iterable instead of only as a list (#37)
=> Miscellaneous improvements to ListValidator, AnyOfValidator, EnumValidator

docs/03-basic-validators.md, src/validataclass/exceptions/misc_exceptions.py, src/validataclass/validators/any_of_validator.py, src/validataclass/validators/enum_validator.py, tests/validators/any_of_validator_test.py, tests/validators/enum_validator_test.py
This PR adds the `case_insensitive` parameter to the `AnyOfValidator` and `EnumValidator`.
If set, string matching will be case-insensitive. The `AnyOfValidator` will return the strings as defined in the list of allowed values.
Additionally, this PR adds the list of allowed values to the `ValueNotAllowedError` raised by the `AnyOfValidator` and `EnumValidator` (unless this list is too long).
=> AnyOfValidator, EnumValidator: Add case_insensitive parameter

src/validataclass/validators/email_validator.py, src/validataclass/validators/regex_validator.py, tests/validators/email_validator_test.py, tests/validators/regex_validator_test.py
#86 
- Optional parameter **allow_empty** added to **EmailValidator**. If set (_allow_empty=True_) empty strings are acceepted as email addresses (e.g. '' or ' ').  Usage:
validator_email = EmailValidator(allow_empty=True)
validator_email.validate('')
- Optional parameter **allow_empty** added to **RegexValidator**. If set (_allow_empty=True_) empty strings are acceepted as input values (e.g. '' or ' '). Usage:
validator_regex = RegexValidator(r'[0-9a-fA-F]+', allow_empty=True)
validator_regex.validate('')
Tests also added.
=> EmailValidator: Add parameter "allow_empty" (#86)

docs/03-basic-validators.md, src/validataclass/exceptions/common_exceptions.py, src/validataclass/validators/__init__.py, src/validataclass/validators/allow_empty_string.py, tests/exceptions/common_exceptions_test.py, tests/validators/allow_empty_string_test.py
#87
New wrapper validator **AllowEmptyString** that allows the empty string as input. 
Usage: 
validator = AllowEmptyString(BooleanValidator())
validator.validate('')  # will return the string ''
validator = AllowEmptyString(BooleanValidator(), default='no value given!')
validator.validate('')  # will return the string "no value given"
Tests also added.
=> New wrapper validator: AllowEmptyString (#87) 

setup.cfg
Due to some minor version updates and version incompatibilities, the test suites are broken. This should fix it.
=> Update testing dependencies to fix test suite

docs/03-basic-validators.md, src/validataclass/validators/__init__.py, src/validataclass/validators/discard_validator.py, tests/validators/discard_validator_test.py
Implements a new special validator `DiscardValidator` that discards any input and always returns a predefined value. (See https://github.com/binary-butterfly/validataclass/issues/92)
=> Implement DiscardValidator

tests/validators/any_of_validator_test.py
This PR only adds some unit tests for the `AnyOfValidator` with an empty list of allowed values (and therefore allowed types).
=> Add unit tests for AnyOfValidator with empty allowed values

docs/03-basic-validators.md, src/validataclass/validators/email_validator.py, tests/validators/email_validator_test.py
This PR adds a `max_length` parameter to the EmailValidator.
It defaults to the same value that was used before (256) and is simply passed to the base StringValidator.
=> EmailValidator: Add max_length parameter

docs/03-basic-validators.md, src/validataclass/validators/any_of_validator.py, src/validataclass/validators/enum_validator.py, tests/validators/any_of_validator_test.py, tests/validators/enum_validator_test.py
This PR implements the change described in https://github.com/binary-butterfly/validataclass/issues/93.
Both the AnyOfValidator and EnumValidator are now case-insensitive by default (when using strings).
**This is a smaller breaking change**, which practically shouldn't affect anyone negatively.
The old parameter `case_insensitive` was **deprecated** and replaced with a new parameter `case_sensitive` (with the opposite meaning, of course). The old parameter is still supported for compatibility, but issues a DeprecationWarning and will be removed in a future version.
=> AnyOfValidator/EnumValidator: Set case-sensitive as default (#93)

docs/03-basic-validators.md, src/validataclass/validators/decimal_validator.py, src/validataclass/validators/float_to_decimal_validator.py, src/validataclass/validators/numeric_validator.py, tests/test_utils.py, tests/validators/decimal_validator_test.py, tests/validators/float_to_decimal_validator_test.py, tests/validators/numeric_validator_test.py
This PR adds a new parameter `rounding` to the `DecimalValidator` and all validators based on it (`FloatToDecimalValidator` and `NumericValidator`) to specify the rounding mode. (See #88.)
It also changes the default rounding mode to `decimal.ROUND_HALF_UP` (before, no rounding mode was specified explicitly, meaning the rounding mode of the current decimal context was used, which usually is `decimal.ROUND_HALF_EVEN` unless changed explicitly).
This change of default behaviour is a minor breaking change, but I'd argue that in most applications the new default value is actually what you wanted in the first place, as Python's default rounding mode seems pretty unintuitive to me.
=> DecimalValidator: Add parameter to specify rounding mode (#88)

.github/workflows/tests.yml, .gitignore, Makefile, setup.cfg, src/validataclass/dataclasses/defaults.py, src/validataclass/helpers/unset_value.py, tests/dataclasses/defaults_test.py, tox.ini
This PR adds official support for Python 3.11 to the library.
Python 3.11 was added as a target for the test environments (both tox for local testing and GitHub actions).
There was one incompatibility that needed to be fixed: In Python 3.11 the `@dataclass` implementation was changed to check for the immutability of default values by checking if they are hashable (i.e. if their classes have an implementation for `__hash__`). This wasn't true for `UnsetValue`, so it couldn't be used as a default value anymore.
=> Add support for Python 3.11

.github/workflows/release.yml, .github/workflows/tests.yml
**DRAFT: This PR should be rebased onto `main` before merging.**
This PR updates all GitHub actions to the latest versions.
This will fix warnings about deprecated Node.js 12 actions.
=> Update GitHub actions to the latest versions

.github/workflows/tests.yml, Makefile, tox.ini
The [tox](https://tox.wiki/) project had a [major update](https://tox.wiki/en/latest/upgrading.html) with some API changes.
This PR adjusts the local test environment (and a small thing in the GitHub actions) to use the new tox API, and simplifies the tox config a bit.
=> Update local test environment for tox 4

docs/05-dataclasses.md, src/validataclass/validators/dataclass_validator.py, tests/validators/dataclass_validator_test.py
Currently, for implementing a context-sensitive `__post_validate__()` method in dataclasses, it is required to accept arbitrary keyword arguments (`**kwargs`). If the `__post_validate__()` method does not accept those, NO context arguments will be passed to it at all.
This can cause confusion and very annoying debugging, and also there's not really a reason to it other than a slightly simpler implementation.
This PR changes this: `__post_validate__()` can now be defined with specific keyword-arguments (i.e. only those that your post validation method actually needs) without accepting `**kwargs`. The `DataclassValidator` will make sure to only pass parameters to the method that it accepts.
It is also allowed to define them as positional arguments (as long as they are not positional-only), …
=> Allow __post_validate__() with context arguments but without **kwargs

docs/03-basic-validators.md, src/validataclass/validators/email_validator.py, tests/validators/email_validator_test.py
This PR adds the optional boolean parameter `to_lowercase` to the `EmailValidator`.
If set, the output email address is automatically converted to lowercase. (Default: False)
=> EmailValidator: Add parameter to convert to lowercase

tests/validators/allow_empty_string_test.py, tests/validators/none_to_unset_value_test.py, tests/validators/noneable_test.py
While I was setting up the dev environment, I ran the tests as described in the readme, and got some error messages from flake8:
```
tests/validators/allow_empty_string_test.py:33:16: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
tests/validators/allow_empty_string_test.py:49:16: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
tests/validators/none_to_unset_value_test.py:34:16: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
tests/validators/noneable_test.py:34:16: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
tests/validators/noneable_test.py:50:16: E721 do not …
```
=> Fix style of type comparisons in some unit tests

.github/workflows/tests.yml, Makefile, setup.cfg, tox.ini
This PR adds Python 3.12 to the test environments, therefore adding official support for Python 3.12.
No further changes for Python 3.12 compatibility were needed.
=> Add official support for Python 3.12

docs/03-basic-validators.md, src/validataclass/validators/datetime_validator.py
This PR updates the Markdown documentation of the DateTimeValidator to reflect the changes from #111.
It also unifies the Markdown documentation and docstring of said validator to make it easier in the future to autogenerate the library documentation from the docstrings.
=> DateTimeValidator: Update documentation; unify docstring with Markdown docs

docs/05-dataclasses.md, src/validataclass/exceptions/__init__.py, src/validataclass/exceptions/meta_exceptions.py, src/validataclass/validators/dataclass_validator.py, tests/validators/dataclass_validator_test.py, tox.ini
This PR implements custom pre-validation in dataclasses by defining a `__pre_validate__()` class method or static method.
See documentation for how it works.
=> Custom pre-validation in dataclasses using __pre_validate__

.github/workflows/release.yml, .github/workflows/tests.yml, Makefile, docs/05-dataclasses.md, setup.cfg, src/validataclass/dataclasses/validataclass.py, src/validataclass/validators/dataclass_validator.py, tests/dataclasses/validataclass_mixin_test.py, tests/dataclasses/validataclass_test.py, tests/validators/dataclass_validator_test.py, tox.ini
Python 3.7 has been EOL since June, 27th 2023.
This PR removes official support for Python 3.7 from the library, which mostly make the use of parentheses around validataclass field tuples unnecessary. Notes about these parentheses were removed from the documentation and tests were adjusted.
This solves #14.
Since this literally breaks support with a Python version, this is a **breaking change**.
=> Drop support for Python 3.7

pyproject.toml, setup.cfg, tests/dataclasses/_helpers.py, tests/dataclasses/defaults_test.py, tests/dataclasses/validataclass_test.py, tests/test_utils.py, tests/validators/dataclass_validator_test.py, tests/validators/datetime_validator_test.py, tests/validators/dict_validator_test.py, tests/validators/discard_validator_test.py, tests/validators/float_validator_test.py, tests/validators/list_validator_test.py, tests/validators/regex_validator_test.py, tests/validators/reject_validator_test.py, tests/validators/validator_test.py, tox.ini
This is a follow up PR to #120, which solves another part of #116.
It adds the unit tests to the targets of mypy and fixes typing issues in those files.
There are two rules that are ignored for now:
1. Untyped definitions are allowed in the unit tests, e.g. you don't need to specify parameter types and the return type for test functions (`def test_something(input_data):` is sufficient). This is because a) the return type is always `None` anyway, and b) for a lot of the test parameters it would make sense to use `Any` anyway.
2. `assignment` errors are ignored. This is the main issue of using validataclass and mypy in a project. Defining a validataclass with e.g. `foo: int = IntegerValidator()` will result in a type error, because mypy thinks we assign an `IntegerValidator` object to an …
=> Add unit tests to mypy targets; fix typing in tests (part of #116)

setup.cfg
The `dateutil` library is currently required by validataclass. However, it's only used in the unit tests, the library itself shouldn't depend on it.
This PR moves `python-dateutil` from install requirements to testing requirements.
=> Move python-dateutil to testing requirements

.github/workflows/release.yml
The release pipeline broke after #122 because it doesn't install `dateutil` when running the unit tests before publishing the package.
This PR fixes this by installing all "testing" extra requirements in the release pipeline.
=> Fix release pipeline by installing all testing requirements

.github/workflows/tests.yml, pyproject.toml, src/validataclass/dataclasses/__init__.py, src/validataclass/exceptions/__init__.py, src/validataclass/helpers/__init__.py, src/validataclass/validators/__init__.py, tests/dataclasses/validataclass_test.py
This PR is another small step towards full mypy support (#116).
It adds the `py.typed` file to make the package PEP 561 compatible (if this file is present, type checkers know that the library is properly typed and can rely on its type annotations).
It also introduces explicit re-exports in `__init__.py` files using the `__all__` variable. This is necessary to enable the `no-implicit-reexport` mypy rule, not just for running mypy on the library itself, but also for projects that use validataclass. It's also just cleaner to explicitly re-export everything.
I also had to add a rule exception to one of the unit test files because mypy reported errors for it. I'm not sure why these errors only popped up now, though.
=> PEP 561 compatibility (py.typed) and explicit re-exports

CHANGELOG.md, README.md
*sigh*
Updates the changelog to re-release the latest update as version 0.11.0, adding a note explaining why version 0.10.1 was yanked.
=> Prepare release of 0.11.0; add note about yanked version 0.10.1
